import { Injectable, Logger, OnApplicationBootstrap } from '@nestjs/common';
import { ProductRegistry, type ProductManifest } from '@helix/core';
import { calendarManifest } from '../../products/calendar/calendar.manifest';
import { meetManifest } from '../../products/meet/meet.manifest';
import { driveManifest } from '../../products/drive/drive.manifest';
import { notesManifest } from '../../products/notes/notes.manifest';

/**
 * Single place where the platform learns which products exist.
 *
 * At 100+ products this list is generated by scanning `src/products/*` rather
 * than hand-maintained; the generator (`pnpm gen:product`) appends the import.
 * Boot fails loudly if the manifest graph is inconsistent, which is how the
 * platform stays coherent without a human reviewing every product change.
 */
@Injectable()
export class ProductRegistryService implements OnApplicationBootstrap {
  private readonly logger = new Logger('registry');
  readonly registry = new ProductRegistry();

  constructor() {
    for (const manifest of [calendarManifest, meetManifest, driveManifest, notesManifest] as ProductManifest[]) {
      this.registry.register(manifest);
    }
  }

  onApplicationBootstrap(): void {
    const issues = this.registry.validate();
    const errors = issues.filter((i) => i.level === 'error');
    for (const issue of issues) {
      const line = `[${issue.product}] ${issue.message}`;
      issue.level === 'error' ? this.logger.error(line) : this.logger.warn(line);
    }
    if (errors.length) {
      throw new Error(`Product registry validation failed with ${errors.length} error(s). Refusing to start.`);
    }
    this.logger.log(`Registered ${this.registry.all().length} products, ${this.registry.permissionCatalogue().length} permissions`);
  }

  /** Powers the app launcher: which products a given tenant may actually open. */
  launcherFor(tier: string, enabled: string[]) {
    return this.registry
      .all()
      .filter((p) => p.availableIn.includes(tier as any))
      .map((p) => ({
        key: p.key,
        name: p.name,
        category: p.category,
        enabled: enabled.includes(p.key),
        ui: p.ui,
      }));
  }
}
